"""empty message

Revision ID: 473a03f1a8b8
Revises: d7c2de8bb417
Create Date: 2020-09-01 23:17:51.051256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473a03f1a8b8'
down_revision = 'd7c2de8bb417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
